# Generated by Django 5.0.3 on 2024-03-29 13:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import inventory.accounts.managers
import inventory.accounts.validators
import inventory.core.model_validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, help_text='Provide a valid email address.', max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', inventory.accounts.managers.InventoryUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(2), inventory.accounts.validators.check_name_symbols_for_non_alphabetical])),
                ('last_name', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(2), inventory.accounts.validators.check_name_symbols_for_non_alphabetical])),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[inventory.core.model_validators.phone_validator])),
                ('is_first_login', models.BooleanField(default=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
