# Generated by Django 5.0.3 on 2024-03-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, help_text='Provide a valid email address.', max_length=254, unique=True),
        ),
    ]
