# Generated by Django 5.0.3 on 2024-03-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryuser',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
