# Generated by Django 5.0.2 on 2024-03-10 06:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('country', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(3)])),
                ('business_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_visible', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
