# Generated by Django 5.0.2 on 2024-03-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
