# Generated by Django 5.0.3 on 2024-03-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_picture',
        ),
    ]
