# Generated by Django 5.0.2 on 2024-03-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
