# Generated by Django 5.0.2 on 2024-03-10 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='owner_name',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
