# Generated by Django 5.0.3 on 2024-03-31 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
