# Generated by Django 5.0.2 on 2024-03-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
