# Generated by Django 5.0.2 on 2024-03-10 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_created_at_alter_device_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='risk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.risk'),
        ),
        migrations.AlterField(
            model_name='device',
            name='support',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.support'),
        ),
    ]
