# Generated by Django 5.0.2 on 2024-03-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_risk_alter_device_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='building',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
