# Generated by Django 5.0.2 on 2024-03-03 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_risk_device_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='devices.operationsystem'),
        ),
    ]
