# Generated by Django 5.0.2 on 2024-03-03 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='os',
        ),
        migrations.AddField(
            model_name='device',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.DeleteModel(
            name='OperationSystem',
        ),
    ]
