# Generated by Django 5.0.3 on 2024-03-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_device_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('In operation', 'In operation'), ('Decommissioned', 'Decommissioned'), ('Pending Setup', 'Pending Setup'), ('Offline', 'Offline'), ('Not defined yet', 'Not defined yet'), ('Exception', 'Exception')], default='Not defined yet', max_length=20),
        ),
    ]
