# Generated by Django 5.0.2 on 2024-03-03 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_business_owner'),
        ('devices', '0007_remove_device_os_device_operating_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.business', verbose_name='business'),
        ),
    ]
