# Generated by Django 5.0.3 on 2024-03-22 12:00

import django.core.validators
import inventory.devices.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2), inventory.devices.validators.validate_no_special_characters]),
        ),
    ]
