# Generated by Django 5.0.3 on 2024-03-22 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_device_operating_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='risk',
        ),
        migrations.RemoveField(
            model_name='device',
            name='support',
        ),
        migrations.AddField(
            model_name='device',
            name='business_processes_at_risk',
            field=models.TextField(blank=True, help_text='Identify the business process that is at risk', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='device',
            name='eol',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='eos',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='impact',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AddField(
            model_name='device',
            name='invoice_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='device',
            name='likelihood',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AddField(
            model_name='device',
            name='purchase_order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sos',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='support_model',
            field=models.TextField(blank=True, help_text='Short description of support model', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.DeleteModel(
            name='Risk',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
    ]
