# Generated by Django 5.0.3 on 2024-03-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_remove_device_risk_remove_device_support_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='invoice_img',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
