# Generated by Django 5.0.3 on 2024-03-23 06:11

import inventory.devices.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_alter_device_invoice_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='invoice_img',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', validators=[inventory.devices.validators.validate_mime_type]),
        ),
    ]
