# Generated by Django 5.0.3 on 2024-03-23 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_alter_device_invoice_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
