# Generated by Django 5.0.3 on 2024-03-28 13:23

import inventory.devices.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_alter_device_manufacturer_alter_device_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='purchase_order_number',
            field=models.IntegerField(blank=True, null=True, validators=[inventory.devices.validators.purchase_order_number_validator]),
        ),
    ]
