# Generated by Django 5.2.3 on 2025-08-31 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)])),
                ('region', models.CharField(choices=[('Asia', 'Asia'), ('Africa', 'Africa'), ('North America', 'North America'), ('South America', 'South America'), ('Europe', 'Europe'), ('Australia', 'Australia'), ('Global', 'Global')], default='Global', max_length=13)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logo/')),
            ],
        ),
    ]
